### PR TITLE
Deferred events

### PR DESCRIPTION
**Pull request by PietroPasotti**
This PR implements an event queue in State.
This is part of the storage simulation and allows you to simulate deferred events.

# Deferred events

Scenario allows you to accurately simulate the Operator Framework's event queue. The event queue is responsible for keeping track of the deferred events. 
On the input side, you can verify that if the charm triggers with this and that event in its queue (they would be there because they had been deferred in the previous run), then the output state is valid.

```python
from scenario import State, deferred


class MyCharm(...):
    ...
    def _on_update_status(self, e):
        e.defer()
    def _on_start(self, e):
        e.defer()

        
def test_start_on_deferred_update_status(MyCharm):
    """Test charm execution if a 'start' is dispatched when in the previous run an update-status had been deferred."""
    out = State(
      deferred=[
            deferred('update_status', 
                     handler=MyCharm._on_update_status)
        ]
    ).trigger('start', MyCharm)
    assert len(out.deferred) == 1
    assert out.deferred[0].name == 'start'
```

You can also generate the 'deferred' data structure (called a `DeferredEvent`) from the corresponding Event (and the handler):

```python
from scenario import Event, Relation

class MyCharm(...):
    ...

deferred_start = Event('start').deferred(MyCharm._on_start)
deferred_install = Event('install').deferred(MyCharm._on_start)
...

# relation events:
foo_relation = Relation('foo') 
deferred_relation_changed_evt = foo_relation.changed_event.deferred(handler=MyCharm._on_foo_relation_changed)
```

On the output side, you can verify that an event that you expect to have been deferred during this trigger, has indeed been deferred.

```python
from scenario import State


class MyCharm(...):
    ...
    def _on_start(self, e):
        e.defer()

        
def test_defer(MyCharm):
    out = State().trigger('start', MyCharm)
    assert len(out.deferred) == 1
    assert out.deferred[0].name == 'start'
```

## Deferring relation events

If you want to test relation event deferrals, some extra care needs to be taken. RelationEvents hold references to the Relation instance they are about. So do they in Scenario. You can use the `deferred` helper to generate the data structure:

```python
from scenario import State, Relation, deferred


class MyCharm(...):
    ...
    def _on_foo_relation_changed(self, e):
        e.defer()

        
def test_start_on_deferred_update_status(MyCharm):
    foo_relation = Relation('foo') 
    State(
      relations=[foo_relation],
      deferred=[
            deferred('foo_relation_changed', 
                     handler=MyCharm._on_foo_relation_changed,
                     relation=foo_relation)
        ]
    )
```

but you can also use a shortcut from the relation event itself, as mentioned above:

```python
from scenario import Relation

class MyCharm(...):
    ...

foo_relation = Relation('foo') 
foo_relation.changed_event.deferred(handler=MyCharm._on_foo_relation_changed)
```

## Fine-tuning
The `deferred` helper Scenario provides will not support out of the box all custom event subclasses, or events emitted by charm libraries or objects other than the main charm class.

For general-purpose usage, you will need to instantiate `DeferredEvent` directly.

```python
from scenario import DeferredEvent

my_deferred_event = DeferredEvent(
   handle_path='MyCharm/MyCharmLib/on/database_ready[1]',
   owner='MyCharmLib',  # the object observing the event. Could also be MyCharm.
   observer='_on_database_ready'
)

```

### CODE REVIEW

**Comment by PietroPasotti** [comment]
For the reviewers:
I'm not quite happy with the level of abstraction of StoredEvent -- it's too low. On the other hand, if you're simulating the events that have been deferred during the previous run, you _are_ dealing with low-level stuff and we're not wizards, so the level will remain low.

That is all data we need to create the of storage notice, I'm not sure there's a way to get around it. Also the snapshot data is very 'raw'. I was wondering if we could support passing in EventBase instances, the issue is that in order to create those, you sometimes need access to Relation instances, etc... and some of those objects might require a live Framework which at that point we don't have yet. 

Ideas?

**Comment by sed-i** [comment]
> ```python
> def test_defer(MyCharm):
>     out = State(
>       event_queue=[
>             StoredEvent('MyCharm/on/update_status[1]', 'MyCharm', '_on_event')
>         ]
>     ).trigger('start', MyCharm)
>     assert len(out.event_queue) == 1
>     assert out.event_queue[0].name == 'start'
>```

- Unclear to me from the example how do `on_event`, `update_status` and `start` related to each other.
- The `'MyCharm/on/update_status[1]'` syntax seems very implicit. Any way to make it more obvious?

**Comment by PietroPasotti** [comment]
> * Unclear to me from the example how do `on_event`, `update_status` and `start` related to each other.

my bad, hasty copy-paste from the other example.

> * The `'MyCharm/on/update_status[1]'` syntax seems very implicit. Any way to make it more obvious?

I agree, but I can't think of a nicer alternative. Ideas are welcome.

**Comment by sed-i** [comment]
- Would it be possible to use a symbol rather than a string? `StoredEvent(MyCharm.on.update_status, ...`
- What does `[1]` mean?

**Comment by benhoyt** [comment]
> I'm not quite happy with the level of abstraction of StoredEvent -- it's too low. On the other hand, if you're simulating the events that have been deferred during the previous run, you are dealing with low-level stuff and we're not wizards, so the level will remain low.

Yeah, agreed, and I share @sed-i's confusion here. (I had to dig into the `Handle` and `save_snapshot` code to see what `MyCharm/on/update_status[1]` meant, and I'm still not sure I understand. :-) So I think you need a simpler and more Pythonic way of creating (stored) events. Can we get by with just event name or whatever the first parameter of `trigger()` is? Surely whatever can be triggered can be deferred? And if they want more, they have to provide an event instance?

Alternatively, you could not provide a way to input saved events. To use it, you'd have to use the output of a previous trigger as the input to the next, something like:

```python
# Ensure "start" defers an event
out = State().trigger('start', MyCharm)
assert len(out.event_queue) == 1
assert out.event_queue[0].name == 'start'

# Ensure deferred event is executed
out = State(event_queue=out.event_queue, other_state=...).trigger('update-status', MyCharm)
assert len(out.event_queue) == 0
# some other assert to ensure deferred event was executed
```

One other comment: "event queue" is quite an overloaded term (I think of Amazon SQS, event loops, etc). Can we call this `deferred_events` or just `deferred` (which would go nicely with `defer()`)?

**Comment by PietroPasotti** [comment]
> Yeah, agreed, and I share @sed-i's confusion here. (I had to dig into the `Handle` and `save_snapshot` code to see what `MyCharm/on/update_status[1]` meant, and I'm still not sure I understand. :-) So I think you need a simpler and more Pythonic way of creating (stored) events. Can we get by with just event name or whatever the first parameter of `trigger()` is? Surely whatever can be triggered can be deferred? And if they want more, they have to provide an event instance?

Yeah the complexity here is that you can defer more than you can trigger. I.e. dispatch can fire a fixed set of events on the charm, but any custom event whatsoever defined by the charm itself or its libs can be deferred (not all of them by the way, some raise exceptions when you attempt to defer them).

Also I would argue that the datatype of the input should be the same as of the output: if `state_in.deferred` is of type `List[Event]`, then `state_out.deferred` should not be `List[SavedEvent]`, so that, as you suggest later, you can reuse outputs as inputs to the next trigger.

Perhaps one way we can make life easier is to add a `get_saved_event` helper. Let me see what I can work out.

> Alternatively, you could not provide a way to input saved events. To use it, you'd have to use the output of a previous trigger as the input to the next, something like:

That is definitely possible already. 
 
> One other comment: "event queue" is quite an overloaded term (I think of Amazon SQS, event loops, etc). Can we call this `deferred_events` or just `deferred` (which would go nicely with `defer()`)?

Good suggestion, I'll go with 'deferred'.

**Comment by PietroPasotti** [comment]
> * Would it be possible to use a symbol rather than a string? `StoredEvent(MyCharm.on.update_status, ...`

Issue with that is that the charm hasn't been instantiated yet at that point, so that'd need to be lazily evaluated or so. 
passing something like a `lambda charm: charm.on.update_status` would work, but is just as obscure.

> * What does `[1]` mean?

an internal operator framework ID, I think it's a unique number for each event a charm has processed

**Comment by PietroPasotti** [comment]
@benhoyt @sed-i 
I added an `Event.deferred` helper that I think makes life a lot easier.

For example you can:
```
foo_relation = Relation('foo') 
relation_changed_evt = foo_relation.changed_event

state = State(
relations=[foo_relation],
deferred=[
     changed_evt.deferred(handler=MyCharm._on_foo_relation_changed)
]
```

**Comment by benhoyt** [comment]
That does seem significantly better -- nice!

**Pull request merged**
